### ISSUE TITLE
環境構築をオフラインで完結できるようにしたい

### ISSUE THREAD

**Issue by uragami-lab** [CodeSeterpie/Kaggle#10]
現状、環境構築をするためにはDockerやSourceTreeのインストーラ、Dockerイメージのダウンロードをする必要があり、その容量は数GBにもなる。  
外で環境構築をする場合はポケットWifiの負担が大きいので、USBに必要な資材をまとめることでオフラインで環境構築を完結できるようにしたい。

**Comment by uragami-lab** [comment]
Dockerイメージについては、[docker  save](https://docs.docker.com/engine/reference/commandline/save/)コマンド、[docker load](https://docs.docker.com/engine/reference/commandline/load/)コマンドで実現できそう。

**Comment by uragami-lab** [comment]
Dockerfile
```
# 基礎となるイメージを設定
FROM jupyter/tensorflow-notebook 

# 不足しているライブラリを追加インストール
RUN pip install xgboost
RUN pip install pandas_profiling
```
docker-compose.yml
```
version: "3"
services:
    # コンテナの名称を設定
    jupyter:
        # イメージ名を明示的に指定する
        image:
           kaggle_houseprices 
        # コンテナ名を明示的に指定する
        container_name:
           kaggle_houseprices 
        # 同じフォルダにあるDockerfileをビルドする。
        build: 
            .
```
上の設定となっている環境で検証した。  
#### 検証内容
FROMで指定した`jupyter/tensorflow-notebook`とdocker-compose.ymlで作成したイメージの二つを`docker save`コマンドを用いてイメージのtarファイルを作成した。  
その後、`docker load`コマンドで2つのイメージの復元をし、`docker-compose up --build`コマンドを実行した。  
結果として、`jupyter/tensorflow-notebook`のダウンロードはなくなったが、`pip`コマンドでインストールした分については、ダウンロードが行われるままだった。  

`jupyter/tensorflow-notebook`だけで4Gbyte有るので、現状でも大幅にダウンロード量を減らすことができることがわかった。
